# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c707ec93768cccf2be0fc64790266a4c4f26d2b35c874c4048fc8fdd78402b97d4687426b87defb8b9aa9c953d2f49f42bb62f20868bfde5474e4c0fe78b6a91

test:
  secret_key_base: cb330d381f7fb0aad7c81db5ea876bce1a03e77584a3fa4136b3b2f4940fc1c3e1944cd2396b1f1ce12ff2f2c44e3dc2fea3f37923c01178dd0f8d376fd77f85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
